name: 'build and publish'

on:
  push:
    branches: ['**']
    tags:
      - 'v**'

jobs:
  build-and-push:
    runs-on: 'windows-2019'
    steps:
      - uses: 'actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579'
      - name: 'Get calculated next version based on commit history'
        id: 'calculated-next-version'
        uses: 'mathieudutour/github-tag-action@v5.5'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          release_branches: 'main'
          default_bump: 'patch'
          dry_run: 'true'
          append_to_pre_release_tag: 'rc-${{ github.run_id }}'
          pre_release_branches: '^((main(?!$)).+|(?!main).+)$'
      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v1'
        with:
          username: 'chrisjohnson00'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'
      - name: 'build container'
        run: |
          docker build . -f Dockerfile_windows -t chrisjohnson00/poc-rabbitmq-consumer:${{ steps.calculated-next-version.outputs.new_tag }}
          docker push chrisjohnson00/poc-rabbitmq-consumer:${{ steps.calculated-next-version.outputs.new_tag }}
